const AppActionsConstants = {
    ADD_RESTAURANT: 'ADD_RESTAURANT',
    ADD_USERNAME: 'ADD_USERNAME',
    CHANGE_USER_NAME: 'CHANGE_USER_NAME',
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    HANDLE_SUBMIT_LOGIN: 'HANDLE_SUBMIT_LOGIN',
    ADD_IMAGE: 'ADD_IMAGE'
};

export {AppActionsConstants}