const AdvancedSearchConstants = {
    CHANGE_LOCATION_SEARCH: 'CHANGE_LOCATION_SEARCH',
    CHANGE_NAME_SEARCH: 'CHANE_NAME_SEARCH',
    ON_CLICK_SEARCH: 'OM_CLICK_SEARCH',
    ON_CHANGE_RADIO_BUTTON_NAME: 'ON_CHANGE_RADIO_BUTTON_NAME',
    ON_CHANGE_RADIO_BUTTON_LOCATION: 'ON_CHANGE_RADIO_BUTTON_LOCATION',
};

export default AdvancedSearchConstants;