const AppConstants = {
    ADD_USER: 'ADD_USER',
    ADD_USER_SAGA: 'ADD_USER_SAGA',
    ADD_RESTAURANT: 'ADD_RESTAURANT',
    ADD_RESTAURANT_SAGA: 'ADD_RESTAURANT_SAGA',
    CHANGE_LOCATION_APP: 'CHANGE_LOCATION_APP',
    CHANGE_LOCATION_APP_SAGA: 'CHANGE_LOCATION_APP_SAGA',
    CHANGE_USERNAME_APP: 'CHANGE_USERNAME_APP',
    CHANGE_USERNAME_APP_SAGA: 'CHANGE_USERNAME_APP_SAGA',
    DELETE_REVIEW: 'DELETE_REVIEW',
    DELETE_REVIEW_SAGA: 'DELETE_REVIEW_SAGA',
    EDIT_REVIEW: 'EDIT_REVIEW',
    EDIT_REVIEW_SAGA: 'EDIT_REVIEW_SAGA',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_SAGA: 'GET_ALL_USERS_SAGA',
    OPEN_DIALOG_EDIT_REVIEW: 'OPEN_DIALOG_EDIT_REVIEW',
    OPEN_DIALOG_DELETE_REVIEW: 'OPEN_DIALOG_DELETE_REVIEW',
    OPEN_EXPAND_REVIEW: 'OPEN_EXPAND_REVIEW',
};

export default AppConstants