const AppConstants = {
    ADD_USER: 'ADD_USER',
    ADD_RESTAURANT: 'ADD_RESTAURANT',
    CHANGE_LOCATION_APP: 'CHANGE_LOCATION_APP',
    CHANGE_USERNAME_APP: 'CHANGE_USERNAME_APP',
    DELETE_REVIEW: 'DELETE_REVIEW',
    EDIT_REVIEW: 'EDIT_REVIEW',
};

export default AppConstants