const AppConstants = {
    ADD_USER: 'ADD_USER',
    ADD_USER_SAGA: 'ADD_USER_SAGA',
    ADD_RESTAURANT: 'ADD_RESTAURANT',
    CHANGE_LOCATION_APP: 'CHANGE_LOCATION_APP',
    CHANGE_USERNAME_APP: 'CHANGE_USERNAME_APP',
    DELETE_REVIEW: 'DELETE_REVIEW',
    EDIT_REVIEW: 'EDIT_REVIEW',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_SAGA: 'GET_ALL_USERS_SAGA',

};

export default AppConstants