const CurrentUserConstants = {
    USER_NAME_ERROR: 'USER_NAME_ERROR',
    CHANGE_USERNAME: 'CHANGE_USERNAME',
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    RESET_CURRENT_STATE: 'RESET_CURRENT_STATE',
    ADD_IMAGE: 'ADD_IMAGE',
};

export {CurrentUserConstants}