const CurrentUserConstants = {
    USER_NAME_ERROR: 'USER_NAME_ERROR',
    CHANGE_USERNAME: 'CHANGE_USERNAME',
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    RESET_CURRENT_STATE: 'RESET_CURRENT_STATE',
    ADD_IMAGE: 'ADD_IMAGE',
    OPEN_DIALOG_NAME: 'OPEN_DIALOG_NAME',
    OPEN_DIALOG_LOCATION: 'OPEN_DIALOG_LOCATION',
    EDITING_NAME: 'EDITING_NAME',
    EDITING_LOCATION: 'EDITING_LOCATION',
    OPEN_DIALOG_DELETE_REVIEW: 'OPEN_DIALOG_DELETE_REVIEW',
};

export {CurrentUserConstants}