const CurrentUserConstants = {
    USER_NAME_ERROR: 'USER_NAME_ERROR',
    CHANGE_USERNAME: 'CHANGE_USERNAME',
    CHANGE_LOCATION_CURRENT: 'CHANGE_LOCATION_CURRENT',
    RESET_CURRENT_STATE: 'RESET_CURRENT_STATE',
    ADD_IMAGE: 'ADD_IMAGE',
    OPEN_DIALOG_NAME: 'OPEN_DIALOG_NAME',
    OPEN_DIALOG_LOCATION: 'OPEN_DIALOG_LOCATION',
    EDITING_NAME: 'EDITING_NAME',
    EDITING_LOCATION: 'EDITING_LOCATION',
    CHANGE_USERNAME_LOGIN: 'CHANGE_USERNAME_LOGIN',
    CHANGE_IMAGE: 'CHANGE_IMAGE',
    CHANGE_ADDRESS: 'CHANGE_ADDRESS',
    SUGGESTIONS_FETCH_REQUEST: 'SUGGESTIONS_FETCH_REQUEST',
    SUGGESTIONS_CLEAR_REQUEST: 'SUGGESTIONS_CLEAR_REQUEST',
};

export {CurrentUserConstants}