const NavigationConstants = {
    ON_CLICK_REGISTER_NAV_BAR: 'ON_CLICK_REGISTER_NAV_BAR',
    ON_CLICK_HOME_NAV_BAR: 'ON_CLICK_HOME_NAV_BAR',
    ON_CLICK_MENU_BUTTON: 'ON_CLICK_MENU_BUTTON',
    ON_CLOSE_MENU: 'ON_CLOSE_MENU',
    ON_CHANGE_ROUTING: 'ON_CHANGE_ROUTING',
    CHANGE_REGISTRATION_SUCCESS: 'CHANGE_REGISTRATION_SUCCESS',
};

export {NavigationConstants}