const NewReviewConstants = {
    CHANGE_PARAM_VALUE: 'CHANGE_PARAM_VALUE',
    CHANGE_NAME: 'CHANGE_NAME',
    ADD_IMAGES: 'ADD_IMAGES',
    RESET_FORM: 'RESET_FORM',
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    NAME_ERROR: 'NAME_ERROR',
};

export default NewReviewConstants