const HomeActionsConstants = {
    ON_CLICK_MENU_BUTTON: 'ON_CLICK_MENU_BUTTON',
    ON_CLOSE_MENU: 'ON_CLOSE_MENU',
    ON_CLICK_MY_PROFILE: 'ON_CLICK_MY_PROFILE',
    ON_CLICK_OTHER_PROFILES: 'ON_CLICK_OTHER_PROFILES',
    ON_CLICK_REVIEWS: 'ON_CLICK_REVIEWS',
    ON_CLICK_NEW_REVIEW: 'ON_CLICK_NEW_REVIEW',
    ON_CLICK_SEARCH: 'ON_CLICK_SEARCH',
    ON_CLICK_LOGOUT: 'ON_CLICK_LOGOUT',
};

export {HomeActionsConstants}