const AppActionsConstants = {
    ADD_RESTAURANT: 'ADD_RESTAURANT',
    ADD_USERNAME: 'ADD_USERNAME',
    CHANGE_USER_NAME: 'CHANGE_USER_NAME',
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    HANDLE_SUBMIT_REGIST: 'HANDLE_SUBMIT_REGIST',
    ADD_IMAGE: 'ADD_IMAGE',
    ON_CLICK_REGISTER_NAV_BAR: 'ON_CLICK_REGISTER_NAV_BAR',
    ON_CLICK_HOME_NAV_BAR: 'ON_CLICK_HOME_NAV_BAR',
};

export {AppActionsConstants}